# Generated by Django 3.2 on 2021-05-11 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(default='')),
                ('Descripcion', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('Nacionalidad', models.TextField(default='')),
                ('F_Muerte', models.TextField(default='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=300)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to=settings.AUTH_USER_MODEL)),
                ('autores', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mipagina.autores')),
            ],
        ),
        migrations.CreateModel(
            name='DescripLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descrpicion', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('presio', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descrpicion', models.TextField(default='')),
                ('img', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descrpicion', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('autores', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mipagina.autores')),
            ],
        ),
        migrations.DeleteModel(
            name='CV',
        ),
    ]
